# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170412_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='change_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
